In [1]:
# Watkins Ch2; Exercise 2.4.3

using LinearAlgebra

A = [6 -1 0 -5 0 0 0; -2 9 -5 0 -2 0 0; 0 -1 3 0 0 -2 0; -2 0 0 5 -2 0 -1; 0 -1 0 -5 12 -1 0; 0 0 -10 0 -2 17 0; 0 0 0 -1 0 0 2]
b = [0; 0; 0; 0; 45; 0; 9]

x = inv(A) * b
residual = b - A * x
display("Residual:")
display(residual)

condition_number = cond(A)
display("Condition No.:")
display(condition_number)

"Residual:"

7-element Vector{Float64}:
 -1.4210854715202004e-14
  1.4210854715202004e-14
 -5.329070518200751e-15
  1.0658141036401503e-14
 -1.4210854715202004e-14
  7.105427357601002e-15
  1.7763568394002505e-15

"Condition No.:"

33.96244580070603

In [2]:
# Watkins Ch2; Exercise 2.5.10 (a)

a = 1
u = 1
b = a + u

i = 0
while b != a
    u = 0.5 * u
    b = a + u
    i = i + 1
end

display(u)
display(i)

1.1102230246251565e-16

53

In [15]:
# Watkins Ch2; Exercise 2.5.10 (b)
a = 1.0

i = 0
while a != Inf
    a = 10 * a
    i = i + 1
end

display(i)

309

In [4]:
# Watkins Ch2; Exercise 2.5.10 (c)
a = 1

i = 0
while a != 0
    a = 0.1 * a
    i = i + 1
end

display(i)

324

In [31]:
# Watkins Ch1; Exercise 1.7.43: in-place LU factorization

using LinearAlgebra
using Random
rng = MersenneTwister(5);

Random.seed!(rng, 2018)

n = 5;

L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
for i=1:n    
    U[i,i] = i
    U[i,i+1:n] = rand(rng, 0:9, n-i)
    L[i,1:i] = rand(rng, 0:9, i)
    L[i,i] = 1
end
A = L*U

5×5 Matrix{Float64}:
 1.0   0.0    2.0    7.0   6.0
 8.0   2.0   25.0   65.0  51.0
 0.0  14.0   66.0   68.0  25.0
 4.0  16.0  107.0  149.0  85.0
 3.0   2.0   30.0   83.0  53.0

In [32]:
for k=1:n
    for j=k+1:n
        for i=k+1:n
            A[i,j] = A[i,j] - (A[i,k] / A[k,k]) * A[k,j]
        end
    end
end

In [34]:
D = Diagonal(diag(A))
M = tril(A)
U = triu(A)

display(M)
display(D)
display(U)

@assert M * inv(D) * U == L * U

5×5 Matrix{Float64}:
 1.0   0.0   0.0   0.0  0.0
 8.0   2.0   0.0   0.0  0.0
 0.0  14.0   3.0   0.0  0.0
 4.0  16.0  27.0   4.0  0.0
 3.0   2.0  15.0  28.0  5.0

5×5 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   2.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   3.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   4.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   5.0

5×5 Matrix{Float64}:
 1.0  0.0  2.0  7.0  6.0
 0.0  2.0  9.0  9.0  3.0
 0.0  0.0  3.0  5.0  4.0
 0.0  0.0  0.0  4.0  1.0
 0.0  0.0  0.0  0.0  5.0

In [4]:
# Wooters Ch3; Q12

using LinearAlgebra

A = [1 0 0 0 1; -1 1 0 0 1; -1 -1 1 0 1; -1 -1 -1 1 1; -1 -1 -1 -1 1]
n = 5

for k=1:n
    for j=k+1:n
        for i=k+1:n
            A[i,j] = A[i,j] - (A[i,k] / A[k,k]) * A[k,j]
        end
    end
end

D = Diagonal(diag(A))
M = tril(A)
U = triu(A)
L = M * inv(D)

display(U)
display(L*U)

5×5 Matrix{Int64}:
 1  0  0  0   1
 0  1  0  0   2
 0  0  1  0   4
 0  0  0  1   8
 0  0  0  0  16

5×5 Matrix{Float64}:
  1.0   0.0   0.0   0.0  1.0
 -1.0   1.0   0.0   0.0  1.0
 -1.0  -1.0   1.0   0.0  1.0
 -1.0  -1.0  -1.0   1.0  1.0
 -1.0  -1.0  -1.0  -1.0  1.0